import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { RunState, TaskState } from "./types.js";

export const DEFAULT_CANVAS_FILE = "quorum-exploration.canvas.tsx";

export async function writeCanvas(canvasPath: string, state: RunState): Promise<void> {
  await mkdir(dirname(canvasPath), { recursive: true });
  await writeFile(canvasPath, renderCanvasSource(state), "utf8");
}

export function renderCanvasSource(state: RunState): string {
  return `${HEADER}\n\nconst STATE: RunState = ${JSON.stringify(state, null, 2)};\n\n${BODY}\n`;
}

const HEADER = `/* AUTO-GENERATED by Quorum. Do not edit by hand; reruns overwrite this file. */
import {
  Card,
  CardBody,
  CardHeader,
  Divider,
  Grid,
  H1,
  H2,
  Pill,
  Row,
  Stack,
  Stat,
  Text,
  useHostTheme,
} from 'cursor/canvas';
import { useMemo } from 'react';

type TaskStatus = 'PENDING' | 'RUNNING' | 'FINISHED' | 'ERROR' | 'SKIPPED';
type Complexity = 'HIGH' | 'MED' | 'LOW';

interface TaskState {
  id: string;
  depends_on: string[];
  complexity: Complexity;
  subtask_prompt: string;
  status: TaskStatus;
  model: string;
  cluster_id?: string;
  task_type?: string;
  startedAt?: number;
  finishedAt?: number;
  durationMs?: number;
  resultText?: string;
  parsedResult?: unknown;
  parseError?: string;
  errorMessage?: string;
  agentId?: string;
  runId?: string;
  requestId?: string;
}

interface RunState {
  title: string;
  startedAt: number;
  finishedAt?: number;
  runOutcome?: 'SUCCESS' | 'FAILED' | 'INTERRUPTED';
  runMessage?: string;
  tasks: TaskState[];
}`;

const BODY = String.raw`
const STATUS_ORDER: TaskStatus[] = ['PENDING', 'RUNNING', 'FINISHED', 'ERROR', 'SKIPPED'];

function statusTone(status: TaskStatus): 'neutral' | 'info' | 'success' | 'warning' {
  switch (status) {
    case 'RUNNING':
      return 'info';
    case 'FINISHED':
      return 'success';
    case 'ERROR':
    case 'SKIPPED':
      return 'warning';
    default:
      return 'neutral';
  }
}

function complexityTone(complexity: Complexity): 'neutral' | 'info' | 'warning' {
  switch (complexity) {
    case 'HIGH':
      return 'warning';
    case 'MED':
      return 'info';
    default:
      return 'neutral';
  }
}

function formatMs(ms?: number): string {
  if (ms === undefined) return '-';
  if (ms < 1000) return ms + 'ms';
  const seconds = ms / 1000;
  if (seconds < 60) return seconds.toFixed(1) + 's';
  const minutes = Math.floor(seconds / 60);
  const rem = Math.round(seconds - minutes * 60);
  return minutes + 'm ' + rem + 's';
}

function elapsed(state: RunState): number {
  return (state.finishedAt ?? Date.now()) - state.startedAt;
}

function resultSummary(task: TaskState): string {
  const parsed = task.parsedResult;
  if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
    const obj = parsed as Record<string, unknown>;
    if (typeof obj.summary === 'string') return obj.summary;
    if (Array.isArray(obj.matches)) return obj.matches.length + ' pattern match(es)';
  }
  if (task.errorMessage) return task.errorMessage;
  if (task.parseError) return task.parseError;
  if (task.resultText) return task.resultText.slice(0, 240);
  return task.status === 'PENDING' ? 'Waiting for dependencies.' : 'No result yet.';
}

function agentRunUrl(task: TaskState): string | undefined {
  if (!task.agentId) return undefined;
  return 'https://cursor.com/agents/' + task.agentId;
}

function clusterGroups(tasks: TaskState[]): Array<{ clusterId: string; tasks: TaskState[] }> {
  const map = new Map<string, TaskState[]>();
  for (const task of tasks) {
    const key = task.cluster_id ?? 'unclustered';
    map.set(key, [...(map.get(key) ?? []), task]);
  }
  return [...map.entries()].map(([clusterId, grouped]) => ({ clusterId, tasks: grouped }));
}

function statusCounts(tasks: TaskState[]): Record<TaskStatus, number> {
  const counts = Object.fromEntries(STATUS_ORDER.map((status) => [status, 0])) as Record<TaskStatus, number>;
  for (const task of tasks) counts[task.status]++;
  return counts;
}

export default function QuorumCanvas() {
  useHostTheme();
  const counts = useMemo(() => statusCounts(STATE.tasks), []);
  const groups = useMemo(() => clusterGroups(STATE.tasks), []);
  const finished = STATE.tasks.filter((task) => task.status === 'FINISHED').length;
  const failed = STATE.tasks.filter((task) => task.status === 'ERROR' || task.status === 'SKIPPED').length;

  return (
    <Stack gap={20}>
      <Stack gap={6}>
        <H1>{STATE.title}</H1>
        <Text tone="secondary" size="small">
          Live Quorum DAG status, Cursor Cloud task runs, and parsed exploration results.
        </Text>
      </Stack>

      <Grid columns={4} gap={12}>
        <Stat label="Tasks" value={String(STATE.tasks.length)} />
        <Stat label="Finished" value={String(finished)} />
        <Stat label="Failed / skipped" value={String(failed)} />
        <Stat label="Elapsed" value={formatMs(elapsed(STATE))} />
      </Grid>

      <Card>
        <CardHeader
          trailing={
            <Pill tone={STATE.runOutcome === 'SUCCESS' ? 'success' : STATE.runOutcome ? 'warning' : 'info'} size="sm" active>
              {STATE.runOutcome ?? 'RUNNING'}
            </Pill>
          }
        >
          Run Status
        </CardHeader>
        <CardBody>
          <Stack gap={8}>
          <Row gap={6} align="center">
            {STATUS_ORDER.map((status) => (
              <Pill key={status} tone={statusTone(status)} size="sm" active={counts[status] > 0}>
                {status}: {counts[status]}
              </Pill>
            ))}
          </Row>
          {STATE.runMessage ? <Text size="small">{STATE.runMessage}</Text> : null}
          </Stack>
        </CardBody>
      </Card>

      <Stack gap={12}>
        <H2>DAG Tasks</H2>
        {groups.map((group) => (
          <Card key={group.clusterId}>
            <CardHeader trailing={<Pill tone="neutral" size="sm">{group.tasks.length} task(s)</Pill>}>
              {group.clusterId}
            </CardHeader>
            <CardBody>
              <Grid columns={2} gap={12}>
                {group.tasks.map((task) => (
                  <Card key={task.id}>
                    <CardHeader trailing={<Pill tone={statusTone(task.status)} size="sm" active>{task.status}</Pill>}>
                      {task.id}
                    </CardHeader>
                    <CardBody>
                      <Stack gap={8}>
                        <Row gap={6} align="center">
                          <Pill tone={complexityTone(task.complexity)} size="sm">{task.complexity}</Pill>
                          <Pill tone="neutral" size="sm">{task.model}</Pill>
                          <Pill tone="neutral" size="sm">{formatMs(task.durationMs)}</Pill>
                        </Row>
                        {task.depends_on.length > 0 ? (
                          <Text tone="secondary" size="small">Depends on: {task.depends_on.join(', ')}</Text>
                        ) : (
                          <Text tone="secondary" size="small">No dependencies</Text>
                        )}
                        <Divider />
                        <Text size="small">{resultSummary(task)}</Text>
                        {task.errorMessage ? <Text tone="secondary" size="small">{task.errorMessage}</Text> : null}
                        {task.parseError ? <Text tone="secondary" size="small">{task.parseError}</Text> : null}
                        {agentRunUrl(task) ? <Text size="small">{agentRunUrl(task)!}</Text> : null}
                        {task.runId ? <Text tone="secondary" size="small">Run: {task.runId}</Text> : null}
                      </Stack>
                    </CardBody>
                  </Card>
                ))}
              </Grid>
            </CardBody>
          </Card>
        ))}
      </Stack>
    </Stack>
  );
}
`;

export function canvasPathFromOutDir(outDir: string): string {
  return `${outDir.replace(/\/+$/, "")}/${DEFAULT_CANVAS_FILE}`;
}
